SARIS/Models/IncidenciasResolucion/IncidenciasResolucionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OrionCoreCableColor.Models.IncidenciasResolucion
{
    public class IncidenciasResolucionViewModel
    {
        public int fiIDTipoRequerimientoResolucion { get; set; }
        public string fcTipoRequerimiento { get; set; }
        public Nullable<int> fiIDCategoriaResolucion { get; set; }
        public string fcDescripcionCategoria { get; set; }
        public string fcToken { get; set; }
        public Nullable<int> fiUbicacion { get; set; }
        public string fcDescripcionUbicacion { get; set; }
        public bool EsEditar { get; set; }
    }
}

SARIS/Controllers/IncidenciasResolucionController.cs
using OrionCoreCableColor.DbConnection;
using OrionCoreCableColor.Models.IncidenciasResolucion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrionCoreCableColor.Controllers
{
    //[Authorize(Roles = "Acceso_Al_Sistema")]
    public class IncidenciasResolucionController : BaseController
    {
        // GET: IncidenciasResolucion
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult CargarListaIndicadores()
        {
            try
            {
                using (var context = new SARISEntities1())
                {
                    var jsonResult = Json(context.sp_IndicadoresResolucion_Lista().Select(x => new IncidenciasResolucionViewModel
                    {
                        fiIDTipoRequerimientoResolucion = x.fiIDTipoRequerimientoResolucion,
                        fcTipoRequerimiento = x.fcTipoRequerimiento,
                        fcToken = x.fcToken,
                        fiIDCategoriaResolucion = x.fiIDCategoriaResolucion,
                        fcDescripcionCategoria = x.fcDescripcionCategoria,
                        fiUbicacion = x.fiUbicacion,
                        fcDescripcionUbicacion = x.fcDescripcionUbicacion,


                    }).ToList(), JsonRequestBehavior.AllowGet);
                    jsonResult.MaxJsonLength = Int32.MaxValue;
                    return jsonResult;
                }
            }
            catch (Exception e)
            {
                return null;
            }
        }


        [HttpGet]
        public ActionResult Crear()
        {
            using (var context = new SARISEntities1())
            {
                ViewBag.ListaCategorias = context.sp_Requerimiento_Catalogo_Categoria_Resolucion().Where(a => a.fiEstado == 1).ToList().Select(x => new SelectListItem { Value = x.fiIDCategoriaDesarrollo.ToString(), Text = x.fcDescripcionCategoria }).ToList();
                ViewBag.Ubicaciones = context.sp_Ubicacion_SubCategoria_Listado().Where(a => a.fiActivo == 1).ToList().Select(x => new SelectListItem { Value = x.fiUbicacion.ToString(), Text = x.fcDescripcionUbicacion }).ToList();

                return PartialView(new IncidenciasResolucionViewModel());
            }
        }



        [HttpPost]
        public ActionResult Crear(IncidenciasResolucionViewModel model)
        {
            using (var context = new SARISEntities1())
            {
                var result = context.sp_IndicadoresResolucion_Insertar(model.fcTipoRequerimiento.Trim(), model.fiIDCategoriaResolucion,0).FirstOrDefault();
                switch (result.fiRequest)
                {
                    case 0:
                        return EnviarResultado(false, "Crear Sub Categoria", "Error al Editar");
                    case 1:
                        return EnviarResultado(true, "Crear Sub Categoria", result.fcRequest);
                    case 2:
                        return EnviarResultado(false, "Crear Sub Categoria", result.fcRequest);
                    default:
                        return EnviarResultado(false, "Crear Sub Categoria", "Error al Editar");
                }

            }


        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            using (var context = new SARISEntities1())
            {
                var model = context.sp_IndicadoresResolucion_Lista().FirstOrDefault(x => x.fiIDTipoRequerimientoResolucion == id);
           
                    ViewBag.ListaCategorias = context.sp_Categorias_IndicidenciasResolucion_Listado().Where(a => a.fiEstado == 1).ToList().Select(x => new SelectListItem { Value = x.fiIDCategoriaResolucion.ToString(), Text = x.fcDescripcionCategoria + " | " + x.fcDescripcion }).ToList();
                    ViewBag.Ubicaciones = context.sp_Ubicacion_SubCategoria_Listado().Where(a => a.fiActivo == 1).ToList().Select(x => new SelectListItem { Value = x.fiUbicacion.ToString(), Text = x.fcDescripcionUbicacion}).ToList();

                    return PartialView("Crear", new IncidenciasResolucionViewModel { fiIDTipoRequerimientoResolucion = model.fiIDTipoRequerimientoResolucion, fcTipoRequerimiento = model.fcTipoRequerimiento.Trim(), fiIDCategoriaResolucion = model.fiIDCategoriaResolucion ?? 0 ,EsEditar = true });
            }
        }

        [HttpPost]
        public ActionResult Editar(IncidenciasResolucionViewModel model)
        {
            using (var context = new SARISEntities1())
            {
                var result = context.sp_IndicadoresResolucion_Editar(model.fiIDTipoRequerimientoResolucion, model.fcTipoRequerimiento.Trim(), model.fiIDCategoriaResolucion, 0).FirstOrDefault();
                switch (result.fiRequest)
                {
                    case 0:
                        return EnviarResultado(false, "Editar Sub Categoria", "Error al Editar");
                    case 1:
                        return EnviarResultado(true, "Editar Sub Categoria", result.fcRequest);
                    case 2:
                        return EnviarResultado(false, "Editar Sub Categoria", result.fcRequest);
                    default:
                        return EnviarResultado(false, "Editar Sub Categoria", "Error al Editar");
                }
            }

        }

        public ActionResult EliminarIndicador(int id)
        {
            using (var context = new SARISEntities1())
            {
                var result = context.sp_Indicadores_Desactivar(id).FirstOrDefault();
                var success = result.fiRequest == 1;

                return EnviarResultado(success, "Eliminar Sub Categoria", success ? "Se Eliminó Satisfactoriamente" : "Error al eliminar");

            }
        }
    }
}

SARIS/Views/IncidenciasResolucion/Crear.cshtml
@model OrionCoreCableColor.Models.IncidenciasResolucion.IncidenciasResolucionViewModel

<!--Modal header-->
<div class="modal-header bg-primary-600 bg-primary-gradient">

    @if (Model.EsEditar)
    {<h2 class="modal-title text-white">Editar Sub Categoria de Resolución</h2> }
    else
    {<h2 class="modal-title text-white">Crear Sub Categoria de Resolución</h2>}
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
</div>

<!--Modal body-->
<div class="modal-body">
    <form id="MyFormModal">
        @Html.HiddenFor(model => model.fiIDTipoRequerimientoResolucion)


        <div class="form-group">
            @Html.LabelFor(model => model.fiIDCategoriaResolucion, htmlAttributes: new { @class = "control-label" })
            <div class="input-group mar-btm" style="width:100%;">

                @Html.DropDownListFor(model => model.fiIDCategoriaResolucion, new SelectList(ViewBag.ListaCategorias, "Value", "Text"), null, new { @class = "form-control input-lg", @style = "width:100%;" })
            </div>
            @Html.ValidationMessageFor(model => model.fiIDCategoriaResolucion, "", new { @class = "text-danger" })
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.fiUbicacion, htmlAttributes: new { @class = "control-label" })
            <div class="input-group mar-btm" style="width:100%;">

                @Html.DropDownListFor(model => model.fiUbicacion, new SelectList(ViewBag.Ubicaciones, "Value", "Text"), null, new { @class = "form-control input-lg", @style = "width:100%;" })
            </div>
            @Html.ValidationMessageFor(model => model.fiUbicacion, "", new { @class = "text-danger" })
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fcTipoRequerimiento, htmlAttributes: new { @class = "control-label" })
            <div class="input-group mar-btm">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fal fa-pencil fa-fw"></i></span>
                </div>

                @Html.EditorFor(model => model.fcTipoRequerimiento, new { htmlAttributes = new { @class = "form-control input-lg" } })
            </div>
            @Html.ValidationMessageFor(model => model.fcTipoRequerimiento, "", new { @class = "text-danger" })
        </div>


        <div class="modal-footer">
            <div class="clearfix" style="width:100%;">
                <button data-dismiss="modal" class="btn btn-link waves-effect waves-themed float-left btn-lg text-danger" type="button"><i class="text-lg ion-close-round"></i></button>
                <button class="btn btn-link btn-lg waves-effect waves-themed float-right text-success"><i class="text-lg ion-checkmark-round"></i></button>
            </div>

        </div>

    </form>
</div>


@Scripts.Render("~/bundles/jqueryval")

<script>
    $("#fiIDCategoriaResolucion").select2({ dropdownParent: $("#MyModalSm") });
    $("#fiUbicacion").select2({ dropdownParent: $("#MyModalSm") });

    $("#MyFormModal").submit(function (event) {
        event.preventDefault();
        if (!$("#MyFormModal").valid()) {
            return false;
        }
        var model = @Html.Raw(Json.Encode(Model));
        model.fiIDTipoRequerimientoResolucion = $("#fiIDTipoRequerimientoResolucion").val();
        model.fcTipoRequerimiento = $("#fcTipoRequerimiento").val();
        model.fiIDCategoriaResolucion = $("#fiIDCategoriaResolucion").val();
        //model.fiUbicacion = $("#fiUbicacion").val();

        var url = "@Url.Action("Crear", "IncidenciasResolucion")";
        if (str2bool('@Model.EsEditar')) {
            url = "@Url.Action("Editar", "IncidenciasResolucion")";
        }

        $.ajax({
            url: url,
            type: 'POST',
            data: JSON.stringify({ model: model }),
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                if (data.Estado) {
                    CerrarModal();
                    $.fn.dataTable.Api("#TablaPrincipal").ajax.reload().draw(false);
                }
                AlertaAjax(data);
            },
            error: function (data) {
                AlertaError();
            },
        });


    });
</script>

SARIS/Views/IncidenciasResolucion/Index.cshtml
@{
    ViewBag.Title = "Lista de Sub Categoria de Resolución";
}

<div class="panel">
    <div class="panel-hdr">
        <h2 class="panel-title"> <i class="fal fa-user fa-fw"></i>Lista de Sub Categorias de Resolución</h2>
        <div class="panel-toolbar " role="menu">
            <a href="javascript:void(0)" onclick="MostrarCrear()" class="btn btn-success"><i class="fal fa-plus fa-fw"></i>Nueva Sub Categoria de Resolución</a>
        </div>
    </div>

    <div class="panel-container" style="padding-top:12px; padding-bottom:15px;">
        <div class="col-lg-12">
            <table class="table table-bordered table-hover table-striped w-100 dataTable dtr-inline" style="width:100%;" id="TablaPrincipal">
                <thead>

                    <tr>
                        <th></th>
                        <th>Causa de Resolucion</th>
                        <th>Categoría</th>
                        @*<th>Ubicación</th>*@
                        <th>Activo</th>

                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>



    </div>
</div>


@section Scripts{

    <script>


        function MostrarCrear() {
            $.ajax({
                url: "@Url.Action("Crear", "IncidenciasResolucion")",
                method: "get",
                success: function (resp) {
                    ShowModalSmall(resp);
                },
                error: function (resp) {
                    alert("Error");
                }
            });
        }

        function Desactivar(id) {
            $.ajax({
                url: "@Url.Action("EliminarIndicador", "IncidenciasResolucion")",
                method: "post",
                data: { id: id },
                success: function (data) {
                    if (data.Estado) {
                        tablaPrincipal.ajax.reload().draw(false);
                    }
                    AlertaAjax(data);
                },
                error: function (resp) {
                    AlertaError();
                }
            });
        }

        function MostrarEditar(id) {
            $.ajax({
                url: "@Url.Action("Editar","IncidenciasResolucion")",
                method: "get",
                data: { id: id },
                success: function (data) {
                    ShowModalSmall(data);
                },
                error: function (resp) {
                    AlertaError();
                }
            });
        }

        var tablaPrincipal = $('#TablaPrincipal').DataTable({

            autoWidth: true,
            responsive: true,
            language: {
                "emptyTable": "No se encontraron resultados.",
                //"searUrlh": '<div class="icon-addon addon-md"><label for="search" class="ion-search"></label>',
                "paginate": {
                    first: "Primero",
                    previous: "Anterior",
                    next: "Siguiente",
                    last: "Ultimo"
                },
                "lengthMenu": " _MENU_ ",
                "info": "Mostrando registros del _START_ al _END_ de _TOTAL_ registros totales.",
                "infoEmpty": "No hay registros para mostrar.",
            },

            order: [[1, "desc"]],
            ajax: {
                url: '@Url.Action("CargarListaIndicadores", "IncidenciasResolucion")',
                method: "Get",
                dataSrc: function (data) {
                    return data;
                }
            },

            columns: [
                        {
                data: null,
                    render: function (data) {
                        var opciones = '<div class="btn-group"> <button class="btn btn-primary btn-xs dropdown-toggle waves-effect waves-themed" data-toggle="dropdown" aria-expanded="false" ' + (data.fcToken == 0 ? 'disabled' : "") + '> Acciones </button>';
                    opciones += '<div class="dropdown-menu">';
                    opciones += '<a class="dropdown-item" href="javascript:void(0)" onclick="MostrarEditar(' + data.fiIDTipoRequerimientoResolucion + ')"> Editar</a>';
                        opciones += '<a class="dropdown-item" href="javascript:void(0)" onclick="Desactivar(' + data.fiIDTipoRequerimientoResolucion +')"> deshabilitar </a>';

                    opciones += '</div></div>';
                    return opciones;
                }
               },

                {
                    data: 'fcTipoRequerimiento'
                },

                {
                    data: 'fcDescripcionCategoria'
                },
                //{
                //    data: 'fcDescripcionUbicacion'
                //},
                {
                    data: null,
                    render: function (data) {
                        if (data.fcToken == 1) {
                            return '<span class="btn-sm btn-block badge badge-success">SI</span>';
                        } else {
                            return '<span class="btn-sm btn-block badge badge-danger">NO</span>';
                        }

                    }
                },


            ]

        });


    </script>
}