SARIS/Models/Usuario/BitacoraSeguridadUsuariosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OrionCoreCableColor.Models.Usuario
{
    public class BitacoraSeguridadUsuariosViewModel
    {
        public int fiIdBitacoraSeguridad { get; set; }
        public string fcNombreCorto { get; set; }
        public DateTime fdFechaCreacion { get; set; }
        public string fcPantallaAfectada { get; set; }
        public string fcObservacion { get; set; }
    }
}

SARIS/Models/Usuario/CambiarContraseñaUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OrionCoreCableColor.Models.Usuario
{
    public class CambiarContraseñaUsuarioViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 4)]
        [DataType(DataType.Password)]
        [Display(Name = "Nueva Contrasena")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar Contrasena")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

SARIS/Controllers/CatalogosController.cs
using OrionCoreCableColor.DbConnection;
using OrionCoreCableColor.Models.Ciudad;
using OrionCoreCableColor.Models.Impacto;
using OrionCoreCableColor.Models.Prioridades;
using OrionCoreCableColor.Models.Usuario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrionCoreCableColor.Controllers
{
    //[Authorize(Roles = "Acceso_Al_Sistema")]
    public class CatalogosController : BaseController
    {
        // GET: Catalogos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BandejaUrgencia()
        {
            return View(); 
        }

        public ActionResult BandejaPrioridades()
        {
            return View();
        }
        public JsonResult PrioridadesBandejaLista()
        {
            try
            {
                using (var context = new SARISEntities1())
                {
                    var jsonResult = Json(context.sp_ListarPrioridad().Select(x => new PrioridadesViewModel
                    {
                        fiIDPrioridad = x.fiIDPrioridad,
                        fcDescripcionPrioridad = x.fcDescripcionPrioridad,
                        fiNivelPrioridad = x.fiNivelPrioridad,
                        fiTiempo = x.fiTiempo,
                        fiActivo = x.fiActivo 

                    }).ToList(), JsonRequestBehavior.AllowGet);
                    jsonResult.MaxJsonLength = Int32.MaxValue;
                    return jsonResult;
                }
            }
            catch (Exception e)
            {
                return null;
            }
        }
        public ActionResult CrearPropiedades()// mi dislexia no supo poner Prioridades y puso propiedades :p ATT: Edgardo Mancia
        {
            using (var contextSaris = new SARISEntities1())
            {
                return PartialView(new PrioridadesViewModel());
            }
        }

        public ActionResult ImpactoBandeja()
        {
            return View();
        }

        public JsonResult ImpactoBandejaLista()
        {
            try
            {
                using (var context = new SARISEntities1())
                {
                    var jsonResult = Json(context.sp_ListarImpacto().Select(x => new ImpactoViewModel
                    {
                        fiIDImpacto = x.fiIDImpacto,
                        fcDescripcionImpacto = x.fcDescripcionImpacto,
                        fiAfectacion = x.fiAfectacion,
                        fiActivo = x.fiActivo,
                        fiNivel = x.fiNivel

                    }).ToList(), JsonRequestBehavior.AllowGet);
                    jsonResult.MaxJsonLength = Int32.MaxValue;
                    return jsonResult;
                }
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public ActionResult Crearinpacto()
        {
            return PartialView();
        }

        public ActionResult BandejaUsuariosVerArea()
        {
            return View();
        }

        public JsonResult UsuarioVerAreaLista()
        {
            try
            {
                using (var context = new SARISEntities1())
                {
                    var jsonResult = Json(context.sp_usuarioVerArea_Lista().Select(x => new UsuariopoAreasViewModel
                    {
                        fiIdUsuarioverArea = x.fiIdUsuarioverArea,
                        fcNombre = x.fcNombre,
                        fcAreas = x.fcAreas,
                        fcIdAreas = x.fcIdAreas


                    }).ToList(), JsonRequestBehavior.AllowGet);
                    jsonResult.MaxJsonLength = Int32.MaxValue;

                    
                    return jsonResult;
                }
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public ActionResult AsignarAreasAUsuario()
        {
            using (var context = new SARISEntities1())
            {
                ViewBag.ListaAreas = context.sp_Areas_Lista().ToList();
                var tick = new UsuariopoAreasViewModel();
                tick.EsEditar = false;
                return PartialView(tick);
            }
        }

        public ActionResult AsignarAreaUsuarioPorUsuario(int idUsuario,int areacontratacion)
        {
            using(var context = new SARISEntities1())
            {
                ViewBag.idusuario = idUsuario;
                ViewBag.idareacontratacion = areacontratacion;
                ViewBag.ListaAreas = context.sp_Areas_Lista().Where(a => a.fiIDArea != areacontratacion).ToList();
                var areasasignadas = context.sp_usuarioVerArea_Lista_ByUsuario(idUsuario).FirstOrDefault().fcIdAreas ?? ""; var newareas = areasasignadas.Split(',').Select(a => Convert.ToInt32(a)).ToList();
                ViewBag.ListaAreasAsignadas = newareas;
                return PartialView();
            }
        }

        public JsonResult EditarAreasaVerPorUsuario(int idusuario, string idareas)
        {
            try
            {
                using (var context = new SARISEntities1())
                {
                    var result = context.sp_usuarioVerArea_Insertar(idusuario, idareas, GetIdUser()).FirstOrDefault();
                    switch (result.fiRequest)
                    {
                        case 0:
                            return EnviarResultado(false, "Areas Asignadas a ver", "Error al Editar");
                        case 1:
                            return EnviarResultado(true, "Areas Asignadas a ver", result.fcRequest);
                        case 2:
                            return EnviarResultado(true, "Areas Asignadas a ver", result.fcRequest);
                        default:
                            return EnviarResultado(false, "Areas Asignadas a ver", "Error al Editar");
                    }
                }
            }
            catch (Exception ex)
            {

                throw;
            }
        }

    }
}

SARIS/Controllers/UsuarioController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using OrionCoreCableColor.DbConnection.CMContext;
using OrionCoreCableColor.Models;
using OrionCoreCableColor.Models.Usuario;
using System.Data.Entity;
using System.Threading.Tasks;
using OrionCoreCableColor.DbConnection;
using Microsoft.AspNet.Identity;
using OrionCoreCableColor.Models.Areas;
using System.Collections.Generic;

namespace OrionCoreCableColor.Controllers
{
    //[Authorize(Roles = "Acceso_Al_Sistema")]
    public class UsuarioController : BaseController
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }



        public JsonResult CargarListaUsuarios()
        {
            try
            {
                using (var context = new OrionSecurityEntities())
                {
                    var jsonResult = Json(context.Usuarios.Select(x => new ListaDeUsuariosViewModel
                    {
                        fiIdUsuario = x.fiIDUsuario,
                        fcPrimerNombre = x.fcPrimerNombre,
                        fcSegundoNombre = x.fcSegundoNombre,
                        fcSegundoApellido = x.fcSegundoApellido,
                        fcPrimerApellido = x.fcPrimerApellido,
                        //FechaNacimiento = x.FechaNacimiento,
                        fiEstado = x.fiEstado,
                        fcBuzondeCorreo = x.fcBuzondeCorreo,
                        fcTelefonoMovil = x.fcTelefonoMovil,
                        UserName = x.AspNetUsers.UserName,
                        NombreRol = x.RolesPorUsuario.Any() ? x.RolesPorUsuario.FirstOrDefault().Roles.Nombre ?? "" : "",
                        fiAreaAsignada = x.fiAreaAsignada,
                        fcAreaAsignada = x.Area.fcDescripcion

                    }).
                    //Where(b => b.fcAreaAsignada != "Soporte").
                    ToList(), JsonRequestBehavior.AllowGet);
                    jsonResult.MaxJsonLength = Int32.MaxValue;
                    return jsonResult;
                }
            }
            catch (Exception e)
            {
                return null;
            }
        }





        [HttpGet]
        public ActionResult CrearUsuario()
        {
            using (var contextSaris = new SARISEntities1())
            {


                using (var context = new OrionSecurityEntities())
                {
                    var usuarioLogueado = GetUser();
                    //var rol = 1; // GetRol(usuarioLogueado.IdRol);
                    //var permisos = GetPermisos(usuarioLogueado.IdRol);
                    ViewBag.ListaAreas = contextSaris.sp_Requerimiento_Areas(1, 1, 1).Where(x => x.fcDescripcion != "Soporte").ToList().Select(x => new SelectListItem { Value = x.fiIDArea.ToString(), Text = x.fcDescripcion }).ToList();
                    ViewBag.ListaRoles = context.Roles.Where(x => x.Activo).Select(x => new SelectListItem { Value = x.Pk_IdRol.ToString(), Text = x.Nombre }).ToList();
                    //if (rol == "Orion_Contratista")
                    //{
                    //    ViewBag.ListaRoles = context.Roles.Where(x => x.Activo && x.Pk_IdRol == 3).Select(x => new SelectListItem { Value = x.Pk_IdRol.ToString(), Text = x.Nombre }).ToList();
                    //}

                    return View(new CrearUsuarioViewModel { fdFechaAlta = DateTime.Now });
                }
            }
        }


        //[HttpGet]
        //public ActionResult AgregarUsuarioTecnico(int id)
        //{
        //    using (var contextOrion = new ORIONDBEntities())
        //    {
        //        using (var context = new OrionSecurityEntities())
        //        {
        //            ViewBag.ListaEmpresas = contextOrion.sp_Empresas_Maestro_Listar().ToList().Select(x => new SelectListItem { Value = x.fiIDEmpresa.ToString(), Text = x.fcNombreComercial }).ToList();
        //            ViewBag.ListaRoles = context.Roles.Where(x => x.Activo && x.Pk_IdRol == 3).Select(x => new SelectListItem { Value = x.Pk_IdRol.ToString(), Text = x.Nombre }).ToList();
        //            return View("CrearUsuario", new CrearUsuarioViewModel { fdFechaAlta = DateTime.Now, fbTecnico = true, fiIdUsuario = id, });
        //        }
        //    }

        //}

        [HttpPost]
        public async Task<ActionResult> CrearUsuario(CrearUsuarioViewModel model)
        {
            try
            {
                using (var context = new OrionSecurityEntities())
                {
                    var user = new ApplicationUser { UserName = model.UserName.Trim(), Email = model.fcBuzondeCorreo.Trim() };
                    var result = await UserManager.CreateAsync(user, model.fcPassword.Trim());
                    var usuario = context.AspNetUsers.FirstOrDefault(x => x.UserName == model.UserName);
                    if (result.Succeeded)
                    {

                        var nuevoUsuario = context.Usuarios.Add(new Usuarios_Maestro
                        {
                            fcPrimerNombre = model.fcPrimerNombre.Trim(),
                            fcSegundoNombre = model.fcSegundoNombre.Trim(),
                            fcPrimerApellido = model.fcPrimerApellido.Trim(),
                            fcSegundoApellido = model.fcSegundoApellido.Trim(),
                            //FechaNacimiento = model.FechaNacimiento,
                            fcNombreCorto = model.UserName,
                            fcCentrodeCosto = "0100",
                            fiIDPuesto = (short)model.IdRol,
                            fiTipoUsuario = 1,
                            fiIDDepartamento = 1,
                            fiIDJefeInmediato = 1,
                            fcUsuarioDominio = model.UserName,
                            fiIDDominioRed = 1,
                            fcPassword = usuario.PasswordHash,
                            fcPasswordToken = user.PasswordHash,
                            fdFechaUltimoCambiodePassword = DateTime.Now,
                            fcBuzondeCorreo = model.fcBuzondeCorreo.Trim(),
                            fiIDDominioCorreo = 1,
                            fcDireccionFisica = "direccion",
                            fcDocumentoIdentificacion = model.fcDocumentoIdentificacion,
                            fdFechaAlta = DateTime.Now,
                            fiIDUsuarioSolicitante = 1,
                            fiIDUsuarioCreador = 1,
                            fiEstado = 1,
                            fdFechaBaja = null,
                            fcTelefonoMovil = model.fcTelefonoMovil,
                            fcToken = Guid.NewGuid().ToString(),
                            fcIdAspNetUser = usuario.Id,
                            fiIDEmpresa = model.fiIDEmpresa ?? 0,
                            fiAreaAsignada = model.fiAreaAsignada




                        });

                        nuevoUsuario.RolesPorUsuario.Add(new RolesPorUsuario
                        {
                            Fk_IdRol = model.IdRol
                        });

                        

                        var ListaPermisos = context.PrivilegiosPorRol.Where(x => x.Fk_IdRol == model.IdRol).Select(z => z.AspNetRoles.Name).ToList();
                        foreach (var permiso in ListaPermisos)
                        {
                            await UserManager.AddToRoleAsync(user.Id, permiso);
                        }

                        var resultado = context.SaveChanges() > 0;
                        var usuariocreado = context.Usuarios.OrderByDescending(a => a.fiIDUsuario).FirstOrDefault();

                        var fiareasadignada = Convert.ToString(model.fiAreaAsignada);
                        using (var contexto = new SARISEntities1())
                        {
                            var usuarioLogueado = contexto.sp_Usuarios_Maestro_PorIdUsuario(GetIdUser()).FirstOrDefault();
                            var resultadoo = contexto.sp_usuarioVerArea_Insertar(usuariocreado.fiIDUsuario, fiareasadignada, GetIdUser()).FirstOrDefault();
                            var guardarbitacora = contexto.sp_BitacoraSeguridadGuardar(GetIdUser(), "Crear Usuario", $"El Usuario {usuarioLogueado.fcNombreCorto} A Creado Al Usuario {usuariocreado.fcNombreCorto}");
                        }

                        return EnviarResultado(resultado, "Crear Usuario");
                    }
                    else
                    {
                        return EnviarResultado(result.Succeeded, result.Errors.FirstOrDefault());

                    }
                }
            }
            catch (Exception e)
            {
                return EnviarResultado(false, e.Message);
            }
        }




        [HttpPost]
        public async Task<ActionResult> CrearTecnico(CrearUsuarioViewModel model)
        {
            try
            {
                using (var contextSaris = new SARISEntities1())
                {

                    model.fiAreaAsignada = contextSaris.sp_UsuarioMaestro_ObtenerIdAreaAsignada(GetIdUser()).FirstOrDefault() ?? 0;
                    using (var context = new OrionSecurityEntities())
                    {
                        var user = new ApplicationUser { UserName = model.UserName.Trim(), Email = model.fcBuzondeCorreo.Trim() };
                        var result = await UserManager.CreateAsync(user, model.fcPassword.Trim());
                        var usuario = context.AspNetUsers.FirstOrDefault(x => x.UserName == model.UserName);
                        if (result.Succeeded)
                        {

SARIS/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "Usuarios";
}


<div class="panel">
    <div class="panel-hdr">
        <h2 class="ui-sortable-handle"> <i class="fal fa-user fa-fw"></i>Lista de Usuarios</h2>
        <div class="panel-toolbar " role="menu">
            @*@if (User.IsInRole("coreseguridad_AccesoAlSistema"))
                {
                    <a href="@Url.Action("CrearUsuario")" class="btn btn-success"><i class="fal fa-plus fa-fw"></i> Nuevo Usuario</a>
                }*@
            <a href="@Url.Action("CrearUsuario")" class="btn btn-success"><i class="fal fa-plus fa-fw"></i> Nuevo Usuario</a>
        </div>
    </div>

    <div class="panel-container">
        <div class="col-lg-12" style="padding-top:12px; padding-bottom:15px;">
            <table class="table table-bordered table-hover table-striped w-100 dataTable dtr-inline" style="width:100%;" id="TablaPrincipal">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Nombre Completo</th>
                        <th>Usuario</th>
                        <th>Area de Contratacion</th>
                        <th>Correo Electronico</th>
                        <th>Fecha de Nacimiento</th>
                        <th>Telefono</th>
                        <th>Rol Usuario</th>
                        <th>Activo</th>


                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>


    </div>
</div>

<div class="panel">
    <div class="panel-hdr">
        <h2 class="ui-sortable-handle"> <i class="fal fa-user fa-fw"></i>Bitacoras Usuarios</h2>
        <div class="panel-toolbar " role="menu">
        </div>
    </div>

    <div class="panel-container">
        <div class="col-lg-12" style="padding-top:12px; padding-bottom:15px;">
            <table class="table table-bordered table-hover table-striped w-100 dataTable dtr-inline" style="width:100%;" id="TablaUsuarioBitacora">
                <thead>
                    <tr>
                        <th></th>
                        <th>Usuario que realizo la accion</th>
                        <th>Fecha</th>
                        <th>Pantalla que accedio</th>
                        <th>Accion que Realizo</th>

                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {

    <script>

        function MostrarEditarInfo(id) {
            $.ajax({
                url: "@Url.Action("EditarInfoUsuario", "Usuario")",
                method: "get",
                data: { id: id },
                success: function (resp) {
                    ShowModalBig(resp);
                },
                error: function (resp) {
                    alert("Error");
                }
            });
        }

        function MostrarEditarInfoLaboral(id) {
             $.ajax({
                 url: "@Url.Action("EditarInfoUsuarioLaboral", "Usuario")",
                 method: "get",
                 data: { id: id },
                 success: function (resp) {
                     ShowModalSmall(resp);
                 },
                 error: function (resp) {
                     alert("Error");
                 }
             });
         }

        function MostrarEditarCuenta(id) {
            $.ajax({
                url: "@Url.Action("EditarCuentaUsuario","Usuario")",
                method: "get",
                data: { id: id },
                success: function (resp) {
                    ShowModalBig(resp);
                },
                error: function (resp) {
                    alert("Error");
                }
            });
        }

        function MostrarCambiarContrasena(id) {
            $.ajax({
                url: "@Url.Action("CambiarContrasenaUsuario","Usuario")",
                method: "get",
                data: { id: id },
                success: function (resp) {
                    ShowModal(resp);
                },
                error: function (resp) {
                    alert("Error");
                }
            });
        }

        function Desactivar(id) {
            $.ajax({
                url: "@Url.Action("DeshabilitarUsuario","Usuario")",
                method: "post",
                data: { id: id },
                success: function (data) {
                    if (data.Estado) {
                        tablaPrincipal.ajax.reload().draw(false);
                    }
                    AlertaAjax(data);
                },
                Urlrror: function (resp) {
                    AlertaError();
                }
            });
        }


        var tablaPrincipal = $('#TablaPrincipal').DataTable({
            autoWidth: true,
            responsive: true,
            language: {
                "emptyTable": "No se encontraron resultados.",
                "searUrlh": '<div class="icon-addon addon-md"><label for="search" class="ion-search"></label>',
                "paginate": {
                    first: "Primero",
                    previous: "Anterior",
                    next: "Siguiente",
                    last: "Ultimo"
                },
                "lengthMenu": " _MENU_ ",
                "info": "Mostrando registros del _START_ al _END_ de _TOTAL_ registros totales.",
                "infoEmpty": "No hay registros para mostrar.",
            },

            order: [[1, "desc"]],
            ajax: {
                url: '@Url.Action("CargarListaUsuarios", "Usuario")',
                method: "Get",
                dataSrc: function (data) {
                    console.log(data);
                    return data;
                }
            },

            columns: [
                {
                    "className": 'details-control',
                    "orderable": false,
                    "data": null,
                    "defaultContent": ''
                    //data: null,
                    //render: function (data) {
                    //    var opt = "";
                    //    opt = `<a class="btn btn-link btn-xs view-control details-productos" href="javascript:void(0)" ><i class="fal fa-plus fa-fw text-success"></i></a>`;
                    //    return opt;
                    //}
                },
                {
                    data: null,
                    render: function (data) {

                        var opciones = '<div class="btn-group"> <button class="btn btn-primary btn-xs dropdown-toggle waves-effect waves-themed" data-toggle="dropdown" aria-expanded="false"> Acciones  </button>';
                        opciones += '<div class="dropdown-menu">';
                        if (data.fiEstado == 1 ) {

                            opciones += '<a href="javascript:void(0)" class="dropdown-item" onclick="MostrarEditarInfo(' + data.fiIdUsuario + ')"> Editar Informacion Personal</a>';
                            opciones += '<a href="javascript:void(0)" class="dropdown-item" onclick="MostrarEditarInfoLaboral(' + data.fiIdUsuario + ')"> Editar Informacion Laboral</a>';
                            opciones += '<a href="javascript:void(0)" class="dropdown-item" onclick="MostrarCambiarContrasena(' + data.fiIdUsuario + ')"> Cambiar Contraseña</a>';
                            opciones += `<a href="javascript:void(0)" class="dropdown-item" onclick="MostrarCrear('${data.fiIdUsuario}','${data.fiAreaAsignada}')">Asignar Areas que puede ver</a>`
                        }

                        opciones += `<a href="javascript:void(0)" class="dropdown-item" onclick="MostrarEditarCuenta(${data.fiIdUsuario})">Editar Cuenta de usuario</a>`;
                        @if (User.IsInRole("coreseguridad_AccesoAlSistema"))
                        {
                            //opciones += '<a href="javascript:void(0)" class="dropdown-item" onclick="MostrarEditarCuenta(' + data.fiIdUsuario + ')"> Editar Cuenta de Usuario</a>';
                        }
                      opciones += '<a href="javascript:void(0)" class="dropdown-item" onclick="Desactivar(' + data.fiIdUsuario + ')"> ' + (data.fiEstado == 1 ? 'Deshabilitar Usuario' : 'Habilitar Usuario') + '</a>';


                        opciones += data.NombreRol == "Orion_Contratista" ? `<a href="@Url.Action("AgregarUsuarioTecnico", "Usuario")/${data.fiIdUsuario}" class="dropdown-item"> Agregar Tecnicos </a>` : "";
                        opciones += '</div></div>';
                        return opciones;
                    }
                },
                {
                    data: null,
                    render: function (data) {

                        return data.fcPrimerNombre + " " + data.fcSegundoNombre + " " + data.fcPrimerApellido + " " + data.fcSegundoApellido;
                    }
                },
                {
                    data: 'UserName'
                },
                {
                    data: 'fcAreaAsignada'
                },


                {
                    data: 'fcBuzondeCorreo'
                },
                {
                    visible: false,
                    data: null,
                    render: function (data) {

                        return '<div style="display:none;">' + moment(data.FechaNacimiento) + '</div>' + moment(data.FechaNacimiento).format("DD/MM/YYYY");
                    }
                },

                {
                    data: 'fcTelefonoMovil'
                },

                {
                    data: null,
                    render: function (data) {

                        return `<span class="btn-sm btn-block badge badge-info">${data.NombreRol}</span>`;


                    }
                },

                {
                    data: null,
                    render: function (data) {
                        if (data.fiEstado) {
                            return '<span class="btn-sm btn-block badge badge-success">SI</span>';
                        } else {
                            return '<span class="btn-sm btn-block badge badge-danger">NO</span>';
                        }

                    }
                },


            ]

        });


        function MostrarCrear(idusuarios, area) {
            console.log(`entro`);
            $.ajax({
                url: "@Url.Action("AsignarAreaUsuarioPorUsuario", "Catalogos")",
                data: { idUsuario: idusuarios, areacontratacion: area},
                method: "get",
                success: function (resp) {
                    ShowModal(resp);
                },
                error: function (resp) {
                    alert("Error");
                }
            });
        }


        $('#TablaPrincipal tbody').on('click',
            'td.details-control',
            function () {
                var table = $.fn.dataTable.Api("#TablaPrincipal");
                var tr = $(this).closest('tr');
                var row = table.row(tr);
                var data = table.row(row).data();
                console.log(data);
                //data.DetallePagoSeguroCafe;
                //for (var item of data.DetallePagoSeguroCafe) {
                //    item.FechaAsegurada = moment(item.FechaAsegurada).format("YYYY-MM-DD");
                //}
                debugger;
                console.log(`usuario del row ${data.fiIdUsuario}`);
                if (row.child.isShown()) {
                    row.child.hide();
                    tr.removeClass('shown');
                } else {
                    tr.addClass('shown');
                    $.ajax({
                        url: '@Url.Action("SubtablaUsuariosAresAVer", "Usuario")',
                        data: { idUsuario: data.fiIdUsuario},
                        method: "GET",
                        success: function (resp) {
                            row.child(resp).show();
                        }
                    });
                }
            }
        );

        var tablaBitacora = $('#TablaUsuarioBitacora').DataTable({
            autoWidth: true,
            responsive: true,
            language: {
                "emptyTable": "No se encontraron resultados.",
                "searUrlh": '<div class="icon-addon addon-md"><label for="search" class="ion-search"></label>',
                "paginate": {
                    first: "Primero",
                    previous: "Anterior",
                    next: "Siguiente",
                    last: "Ultimo"
                },
                "lengthMenu": " _MENU_ ",
                "info": "Mostrando registros del _START_ al _END_ de _TOTAL_ registros totales.",
                "infoEmpty": "No hay registros para mostrar.",
            },

            order: [[0, "desc"]],
            ajax: {
                url: '@Url.Action("DataBitacoraUsuario", "Usuario")',
                method: "Get",
                dataSrc: function (data) {
                    console.log(data);
                    return data;
                }
            },

            columns: [
                {
                    data: 'fiIdBitacoraSeguridad'
                },
                {
                    data: 'fcNombreCorto'
                },
                {
                    visible: true,
                    data: null,
                    render: function (data) {

                        return moment(data.fdFechaCreacion).format("DD/MM/YYYY HH:mm");
                    }
                },

                {
                    data: 'fcPantallaAfectada'
                },
                {
                    data: 'fcObservacion'
                },
            ]

        });

    </script>
}