SARIS/Controllers/BaseController.cs
using Microsoft.AspNet.SignalR;
using OrionCoreCableColor.App_Helper;
using OrionCoreCableColor.App_Services.EmailService;
using OrionCoreCableColor.App_Services.ReportesService;
using OrionCoreCableColor.DbConnection;
using OrionCoreCableColor.DbConnection.CMContext;
using OrionCoreCableColor.Models.Base;
using OrionCoreCableColor.Models.EmailTemplateService;
using OrionCoreCableColor.Models.Ticket;
using OrionCoreCableColor.Models.Usuario;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Cors;
using System.Web.Mvc;


namespace OrionCoreCableColor.Controllers
{
    public class BaseController : Controller
    {

        private DbServiceConnection _connection;
        public BaseController()
        {
            
            
        }
        protected override IAsyncResult BeginExecuteCore(AsyncCallback callback, object state)
        {
            return base.BeginExecuteCore(callback, state);
        }

        public void enviarMiUsuario(InfoUsuarioViewModel model)
        {
            var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificacionesHub>();
            hubContext.Clients.All.enviarMiUsuario(model);
        }


        [HttpPost]
        public JsonResult RegistrarUsuariosLogueados(InfoUsuarioViewModel model, string usuarioPeticion)
        {
          

            var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificacionesHub>();
            hubContext.Clients.All.insertarUsuarios(model, usuarioPeticion);



            return Json(true, JsonRequestBehavior.AllowGet);
        }


        //public List<ListaDeUsuariosViewModel> GetUsuariosLogueados()
        //{
        //    //return MemoryLoadManager.ListaUsuarios.Where(x => x.InfoUsuario.Any()).ToList();
        //}
        [AllowAnonymous]
        public void EnviarNotificacion(string mensajeNotificacion)
        {
            var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificacionesHub>();
            hubContext.Clients.All.enviarNotificacion(mensajeNotificacion);
        }

        public string EnviarFormularioSignalR<T>(ObjSignalRModalViewModel model) where T : class
        {
            try
            {
                var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificacionesHub>();
                hubContext.Clients.All.mostrarModal(new { model = (T)model.Obj, url = model.Url, user = model.InfoUsuario });
                return "Bueno";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

        }

        public string EnviarFormularioSignalRStruct<T>(ObjSignalRModalViewModel model) where T : struct
        {
            try
            {
                var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificacionesHub>();
                hubContext.Clients.All.mostrarModal(new { model = model.Obj, url = model.Url, user = model.InfoUsuario });
                return "Bueno";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

        }

        public JsonResult EnviarResultado(bool resultado, string Titulo)
        {
            return Json(new MensajeRespuestaViewModel
            {
                Titulo = Titulo,
                Mensaje = resultado ? "Action Successful" : "Error",
                Estado = resultado

            }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult EnviarResultado(bool resultado, string Titulo, string Mensaje)
        {
            return Json(new MensajeRespuestaViewModel
            {
                Titulo = Titulo,
                Mensaje = Mensaje,
                Estado = resultado,
            }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult EnviarResultado(bool resultado, string Titulo, string Mensaje, int Id)
        {
            return Json(new MensajeRespuestaViewModel
            {
                Titulo = Titulo,
                Mensaje = Mensaje,
                Estado = resultado,
                Id = Id
            }, JsonRequestBehavior.AllowGet);

        }

        [AllowAnonymous]
        public void EscribirEnLogJson(string mensaje)
        {
            var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificacionesHub>();
            hubContext.Clients.All.recibirNoficicacionJson(new NotificacionViewModel
            {
                fiIDUsuario = GetIdUser(),
                fdFechaTransaccion = DateTime.Now,
                fcUsuario = ((User?.Identity?.Name ?? "") == "") ? "sistembot" : User?.Identity?.Name ?? "sistembot",
                fcOperacion = mensaje,
                fcTipoTransaccion = "Transaccion",
                fcClase = "success"
            });
        }
        public JsonResult EnviarResultado(bool resultado, string Titulo, string Mensaje, string Correlativo)
        {
            return Json(new MensajeRespuestaViewModel
            {
                Titulo = Titulo,
                Mensaje = Mensaje,
                Estado = resultado,
                Correlativo = Correlativo
            }, JsonRequestBehavior.AllowGet);

        }


        public JsonResult EnviarException(Exception e, string Titulo)
        {

            if (MemoryLoadManager.Produccion)
            {
                RegistrarError(e);
            }


            return Json(new MensajeRespuestaViewModel
            {
                Titulo = Titulo,
                Mensaje = (e.InnerException?.Message ?? e.Message) + ": " + e.StackTrace,
                Estado = false,

            }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult EnviarListaJson(object e)
        {
            var jsonResult = Json(e, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;

        }

        public List<string> PreguntasAleatorias(List<string> lista, string opcionCorrecta, int tipoLista)
        {
            Random rand = new Random();
            //preguntas


            //si es 1 hacer randon de respuestas
            if (tipoLista == 1)
            {
                lista = lista.Where(x => x != opcionCorrecta).Select(x => x).ToList();
                var listaArreglo = lista.ToArray();
                int cantidaddeElementos = lista.Count;
                int numeroAlzar = rand.Next(1, cantidaddeElementos);
                int numeroAlzar2 = rand.Next(1, cantidaddeElementos);
                string opcion1AlAzar = listaArreglo[numeroAlzar];
                string opcion2AlAzar = listaArreglo[numeroAlzar2];
                while (numeroAlzar2 == numeroAlzar)
                {
                    numeroAlzar2 = rand.Next(1, cantidaddeElementos);
                    opcion2AlAzar = listaArreglo[numeroAlzar2];
                }

                var ListaRetornar = new List<string> { opcion1AlAzar, opcion2AlAzar, opcionCorrecta };

                ListaRetornar = ListaRetornar.OrderBy(x => rand.Next()).ToList();
                return ListaRetornar;
            }
            // sino solo retornar lista
            else
            {
                return lista;
            }


        }
        public string[] PreguntasATomar()
        {
            Random rand = new Random();
            List<int> preguntasAgregada = new List<int>();
            int numeroPregunta = rand.Next(1, 7);
            preguntasAgregada.Add(numeroPregunta);
            int numeroPregunta2 = rand.Next(1, 7);
            while (preguntasAgregada.Contains(numeroPregunta2))
            {
                numeroPregunta2 = rand.Next(1, 7);
            }
            preguntasAgregada.Add(numeroPregunta2);

            int numeroPregunta3 = rand.Next(1, 7);
            preguntasAgregada.Add(numeroPregunta3);
            while (preguntasAgregada.Contains(numeroPregunta3))
            {
                numeroPregunta3 = rand.Next(1, 7);
            }


            
            var ListadoSeleccionadoPreguntas = new List<string>() { "Vive", "Trabaja", "Parentesco", "Estado Civil", "Ciudad", "Tiene Hijos" }.ToArray();
            string pregunta1Seleccionada = ListadoSeleccionadoPreguntas[numeroPregunta - 1];
            string pregunta2Seleccionada = ListadoSeleccionadoPreguntas[numeroPregunta2 - 1];
            string pregunta3Seleccionada = ListadoSeleccionadoPreguntas[numeroPregunta3 - 1];

            return new List<string>() { pregunta1Seleccionada, pregunta2Seleccionada, pregunta3Seleccionada }.ToArray();



        }


        public List<int> ListaDias()
        {
            var lista = new List<int>();
            for (int i = 1; i <= 31; i++)
            {
                lista.Add(i);
            }
            return lista;
        }
        public List<int> ListaMeses()
        {
            var lista = new List<int>();
            for (int i = 1; i <= 12; i++)
            {
                lista.Add(i);
            }
            return lista;
        }
        public List<int> ListaAnio()
        {
            int anioActual = DateTime.Now.Year;
            int aniolimite = anioActual - 40;
            var lista = new List<int>();
            for (int i = anioActual; i >= aniolimite; i--)
            {
                lista.Add(i);
            }
            return lista;
        }

        public void agregarCreacionTicket(int idticket)// para cuendo se crea el ticket
        {
            //var model = contexto.sp_Solicitudes_Bandeja_ObtenerPorIDSolicitud(fiIDSolicitud).FirstOrDefault();
            //var model = _connection.SarisContext.sp_Requerimientos_Bandeja_ByID(1,1,idequifax).FirstOrDefault();

            var listaTicket = new List<TicketMiewModel>();
            try

SARIS/Views/Shared/_PartialHeader.cshtml
<style>
    .green-background {
        background-color: #1dc9b7; /* Fondo verde */
        border-radius: 50%; /* Fondo redondeado */
        padding: 7px; /* Espaciado interno para que el ícono no quede pegado al borde */
        color: white !important; /* Color blanco para el ícono */
    }

    .grey-background {
        background-color: #868e96; /* Fondo Gris */
        border-radius: 50%; /* Fondo redondeado */
        padding: 5px; /* Espaciado interno para que el ícono no quede pegado al borde */
        color: white !important; /* Color blanco para el ícono */
    }

</style>

<header class="page-header" role="banner">
    <div class="page-logo">
        <a href="#" class="page-logo-link press-scale-down d-flex align-items-center position-relative"
           data-toggle="modal" data-target="#modal-shortcut">
            <img src="img/logo.png" alt="SmartAdmin WebApp" aria-roledescription="logo">
            <span class="page-logo-text mr-1">SmartAdmin WebApp</span>
            <span class="position-absolute text-white opacity-50 small pos-top pos-right mr-2 mt-n2"></span>
            <i class="fal fa-angle-down d-inline-block ml-1 fs-lg color-primary-300"></i>
        </a>
    </div>
    <div class="hidden-md-down dropdown-icon-menu position-relative">
        <a href="#" class="header-btn btn js-waves-off" data-action="toggle"
           data-class="nav-function-hidden" title="Hide Navigation">
            <i class="ni ni-menu"></i>
        </a>
        <ul>
            <li>
                <a href="#" class="btn js-waves-off" data-action="toggle"
                   data-class="nav-function-minify" title="Minify Navigation">
                    <i class="ni ni-minify-nav"></i>
                </a>
            </li>
            <li>
                <a href="#" class="btn js-waves-off" data-action="toggle"
                   data-class="nav-function-fixed" title="Lock Navigation">
                    <i class="ni ni-lock-nav"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="hidden-lg-up">
        <a href="#" class="header-btn btn press-scale-down" data-action="toggle" data-class="mobile-nav-on">
            <i class="ni ni-menu"></i>
        </a>
    </div>
    <div class="ml-auto d-flex">
        <div class="">
            <a href="#" class="header-icon row" data-toggle="dropdown" id="campanaNotificacion" aria-expanded="false">
                <span id="btnNotificacion" class="btn-sm badge">Desactivo</span>
                <i id="campana" class="fal fa-bell-on "></i>

            </a>
            @*<div class="dropdown-menu dropdown-menu-animated dropdown-xl" style="">
            <div class="dropdown-header bg-trans-gradient d-flex justify-content-center align-items-center rounded-top mb-2">
                <h4 class="m-0 text-center color-white">
                    <label id="noLeidos" style="display:none;"></label>
                    <small class="mb-0 opacity-80">User Notifications</small>
                </h4>
            </div>

            <div class="tab-content tab-notification">
                <div class="tab-pane p-3 text-center">
                    <h5 class="mt-4 pt-4 fw-500">
                        <span class="d-block fa-3x pb-4 text-muted">
                            <i class="ni ni-arrow-up text-gradient opacity-70"></i>
                        </span> Select a tab above to activate
                        <small class="mt-3 fs-b fw-400 text-muted">
                            This blank page message helps protect your privacy, or you can show the first message here automatically through
                            <a href="#">settings page</a>
                        </small>
                    </h5>
                </div>
                <div class="tab-pane active" id="tab-messages" role="tabpanel">
                    <div class="custom-scroll h-100">
                        <ul class="notification" id="listNotificaciones" style="overflow: hidden; width: auto; height: 100%;">
                        </ul>
                        <div class="slimScrollBar" style="background: rgba(0, 0, 0, 0.6); width: 4px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 4px;"></div><div class="slimScrollRail" style="width: 4px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(250, 250, 250); opacity: 0.2; z-index: 90; right: 4px;"></div>
                    </div>
                </div>


            </div>
            <div class="py-2 px-3 bg-faded d-block rounded-bottom text-right border-faded border-bottom-0 border-right-0 border-left-0">
                <a href="#" class="fs-xs fw-500 ml-auto">view all notifications</a>
            </div>
        </div>*@
        </div>
        <div>


            <a href="#" data-toggle="dropdown" title="@User.Identity.Name" class="header-icon d-flex align-items-center justify-content-center ml-5">
                <div class="username hidden-xs color-black">@User.Identity.Name</div>
                <span class="mr-2">
                    &#160;
                    <i class="fal fa-user-alt"></i>
                </span>
            </a>


            <div class="dropdown-menu dropdown-menu-animated dropdown-lg">
                <div class="dropdown-header bg-trans-gradient d-flex flex-row py-4 rounded-top">
                    <div class="d-flex flex-row align-items-center mt-1 mb-1 color-white">
                        <span class="mr-2">
                            <img src="~/Content/img/AvatarUsuario/5.png"
                                 class="rounded-circle profile-image" alt="Profile">
                        </span>

                        <div class="info-card-text">
                            <div class="fs-lg text-truncate text-truncate-lg">@User.Identity.Name</div>
                            @*<span class="text-truncate text-truncate-md opacity-80">@User.Identity.IsAuthenticated</span>*@
                        </div>
                    </div>
                </div>
                <div class="dropdown-divider m-0"></div>
                <a class="dropdown-item fw-500 pt-3 pb-3" href="@Url.Action("LogOff","Account")">
                    <span data-i18n="drpdwn.page-logout">Cerrar Sesión</span>
                </a>
            </div>
        </div>
    </div>
</header>

SARIS/Views/Shared/_PartialModal.cshtml
<style>
    /* Important part */
    .modal-dialog {
        overflow-y: initial !important
    }

    .modal-body {
        /*height: 80vh;*/
        overflow-y: auto;
    }
</style>



<div class="modal fade" id="MyModalBig2"tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-xl" role="document" id=""style="width: 90%;">
        <div class="modal-content" id="MyModalContentBig2">


        </div>
    </div>
</div>

<div class="modal fade" id="MyModalImage" tabindex="-1" role="dialog" data-backdrop="false" aria-labelledby="myModalLabel" style="z-index: 2150">
    <div class="modal-dialog modal-xl" role="document">
        
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fal fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <center>
                    <h3 id="TituloImagen">Hola</h3>
                    <img id="ImageBig" src="" class="img-responsive img-thumbnail" style="width:auto; height:auto;" />
                </center>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="MyModalBig" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="false" data-keyboard="false" style="z-index: 1040">
    <div class="modal-dialog modal-xl">
        <div class="modal-content" id="MyModalContentBig">
            <!-- Contenido del modal grande -->
        </div>
    </div>
</div>

<div class="modal fade" id="MyModalBigSignalR" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content" id="MyModalContentBigSignalR">


        </div>
    </div>
</div>


<div class="modal fade" id="MyModalSm" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sm">
        <div class="modal-content" id="MyModalContentSmall">


        </div>
    </div>
</div>

<div class="modal fade" id="MyModal" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content" id="MyModalContent">

        </div>
    </div>
</div>


<div class="modal fade" id="MyModalBig3" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog  modal-lg">
        <div class="modal-content" id="MyModalContentBig3">


        </div>
    </div>
</div>





<div class="modal fade" id="MyModalContrato" tabindex="-1" z-index="" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog  modal-xl" role="document" id="">
        <div class="modal-content" id="">
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="DestruirContenido()">
                    <span aria-hidden="true"><i class="fal fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <center>
                    <h3 id="TituloContrato">Hola</h3>
                    <div id="divContrato">

                    </div>

                </center>

            </div>
        </div>
    </div>
</div>

<!--<div class="modal fade default-example-modal-left-sm" id="ModalLeft" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-left modal-dialog-scrollable modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title h4" id="titulomodalIzquierda">Large right side modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fal fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body" id="bodyModalIzquierda">
                
            </div>
            <div class="modal-footer">-->
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>*@
            <!--</div>
        </div>
    </div>
</div>-->

<div class="modal fade default-example-modal-right" id="ModalLeft" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-right modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title h4"  id="titulomodalIzquierda" >Large right side modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fal fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body" id="bodyModalIzquierda">
                
                
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>*@
            </div>
        </div>
    </div>
</div>




<div class="modal fade" id="MyModalViewer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="TituloArchivo" class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fal fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body text-center">
                <div id="divContenidoArchivo"></div>
            </div>
        </div>
    </div>
</div>



<script>
  
    function ShowBigImage(boton) {
        
        var sourc = $(boton).attr('src');
        $("#TituloImagen").text($(boton).attr("data-Description"));
        $('#ImageBig').attr('src', sourc);
        $('#MyModalImage').modal("show");
    }

    function ShowBigImageSrc(src){
        $('#ImageBig').attr('src', src);
        $('#MyModalImage').modal("show");
    }

    function ShowBigPdf(descripcion, carpeta, tipe = "application/pdf") {
        debugger;
        @*$.ajax({
            url:"@Url.Action("GetContentDocument","Base")",
            type: "Get",
            data: { tipo: "pdf", carpeta: carpeta, nombreArchivo: descripcion },
            success: function (resp) {
                
            }
        });*@

        $("#divContrato").empty();
        var embed = $(`<embed src="" id="DocumentoBig" type="${tipe}"  class="img-responsive img-thumbnail" style="width:100%;height:500px;" />`);
        $("#TituloContrato").text(descripcion);
        debugger;
        //$(embed).attr('src', "data:application/pdf;base64," + resp);
        $(embed).attr('src', carpeta);
        $(embed).css("height", window.innerHeight - (window.innerHeight * 0.25) + "px");
        $("#divContrato").append(embed);
        $('#MyModalContrato').modal("show");
        
        
    }

    function ShowLeftModal(descripcion, Titulo) {
        $(`#bodyModalIzquierda`).empty();
        //$("#bodyModalIzquierda .modal-body").css("height", '80vh');
        $("#bodyModalIzquierda").html(descripcion);
        $("#titulomodalIzquierda").text(Titulo);
        $("#ModalLeft").modal("show");
    }

    function DestruirContenido()
    {
        debugger;
        $("#divContrato").empty();
    }



    function ShowFileViewer(nombreArchivo, extensionArchivo, urlArchivo) {
        // Obtener el tipo MIME basado en la extensión
        const tipoArchivo = getMimeTypeByExtension(extensionArchivo);

        // Establecer el título del modal
        $("#TituloArchivo").text(nombreArchivo);

        // Limpiar contenido previo
        $("#divContenidoArchivo").empty();

        // Generar contenido dinámico basado en el tipo de archivo
        let contenido = "";

        if (tipoArchivo.startsWith("image/")) {
            contenido = `<img src="${urlArchivo}" class="img-fluid img-thumbnail" style="max-height: 500px;"/>`;
        } else if (tipoArchivo === "application/pdf") {
            contenido = `<embed src="${urlArchivo}" type="application/pdf" style="width: 100%; height: 500px;" />`;
        } else if (tipoArchivo.startsWith("video/")) {
            contenido = `<video controls style="width: 100%; max-height: 500px;">
                        <source src="${urlArchivo}" type="${tipoArchivo}">
                        Tu navegador no soporta reproducción de video.
                     </video>`;
        } else if (
            tipoArchivo === "application/msword" ||
            tipoArchivo === "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ||
            tipoArchivo === "application/vnd.ms-excel" ||
            tipoArchivo === "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        ) {
            contenido = `<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=${encodeURIComponent(
                urlArchivo
            )}" style="width: 100%; height: 500px; border: none;"></iframe>`;
        } else {
            contenido = `<p>Tipo de archivo no soportado para vista previa.</p>`;
        }

        // Insertar contenido en el modal
        $("#divContenidoArchivo").html(contenido);

        // Mostrar el modal
        $("#MyModalViewer").modal("show");
    }


    function getMimeTypeByExtension(extension) {
        return mimeTypes[extension.toLowerCase()] || 'application/octet-stream'; // Valor por defecto para no reconocidos
    }

    const mimeTypes = {
        'jpeg': 'image/jpeg',
        'jpg': 'image/jpeg',
        'png': 'image/png',
        'gif': 'image/gif',
        'pdf': 'application/pdf',
        'doc': 'application/msword',
        'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'xls': 'application/vnd.ms-excel',
        'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'mp4': 'video/mp4',
        'avi': 'video/x-msvideo',
        'mkv': 'video/x-matroska',
        'txt': 'text/plain',
        'csv': 'text/csv',
        // Agregar más si es necesario
    };

</script>